#ifndef ARCANUM_GAME_CRITTER_H_
#define ARCANUM_GAME_CRITTER_H_

#include "game/lib/object.h"

typedef enum SocialClass {
    SOCIAL_CLASS_NOBLE,
    SOCIAL_CLASS_PRIEST,
    SOCIAL_CLASS_WIZARD,
    SOCIAL_CLASS_TECHNOLOGIST,
    SOCIAL_CLASS_SHOPKEEPER,
    SOCIAL_CLASS_GUARD,
    SOCIAL_CLASS_CITY_DWELLER,
    SOCIAL_CLASS_VILLAGER,
    SOCIAL_CLASS_BEGGAR,
    SOCIAL_CLASS_THIEF,
    SOCIAL_CLASS_BANDIT,
    MAX_SOCIAL_CLASS,
} SocialClass;

typedef enum EncumbranceLevel {
    ENCUMBRANCE_LEVEL_NONE,
    ENCUMBRANCE_LEVEL_LIGHT,
    ENCUMBRANCE_LEVEL_MODERATE,
    ENCUMBRANCE_LEVEL_MEDIUM,
    ENCUMBRANCE_LEVEL_SIGNIFICANT,
    ENCUMBRANCE_LEVEL_HEAVY,
    ENCUMBRANCE_LEVEL_SEVERE,
    MAX_ENCUMBRANCE_LEVEL,
} EncumbranceLevel;

void critter_debug_obj(object_id_t obj);

#endif /* ARCANUM_GAME_CRITTER_H_ */
