#ifndef ARCANUM_GAME_MATERIAL_H_
#define ARCANUM_GAME_MATERIAL_H_

typedef enum Material {
    MATERIAL_STONE,
    MATERIAL_BRICK,
    MATERIAL_WOOD,
    MATERIAL_PLANT,
    MATERIAL_FLESH,
    MATERIAL_METAL,
    MATERIAL_GLASS,
    MATERIAL_CLOTH,
    MATERIAL_LIQUID,
    MATERIAL_PAPER,
    MATERIAL_GAS,
    MATERIAL_FORCE,
    MATERIAL_FIRE,
    MATERIAL_POWDER,
    MATERIAL_COUNT,
} Material;

#endif /* ARCANUM_GAME_MATERIAL_H_ */
