#include "game/obj_flags.h"

#include "game/obj.h"

#define STRINGIFY(sym) #sym

// 0x5B9FBC
const char* obj_flags_fields_lookup_tbl_keys[OFS_COUNT] = {
    /*           OFS_FLAGS */ "obj_f_flags",
    /*     OFS_SPELL_FLAGS */ "obj_f_spell_flags",
    /*      OFS_WALL_FLAGS */ "obj_f_wall_flags",
    /*    OFS_PORTAL_FLAGS */ "obj_f_portal_flags",
    /* OFS_CONTAINER_FLAGS */ "obj_f_container_flags",
    /*   OFS_SCENERY_FLAGS */ "obj_f_scenery_flags",
    /*      OFS_ITEM_FLAGS */ "obj_f_item_flags",
    /*    OFS_WEAPON_FLAGS */ "obj_f_weapon_flags",
    /*      OFS_AMMO_FLAGS */ "obj_f_ammo_flags",
    /*     OFS_ARMOR_FLAGS */ "obj_f_armor_flags",
    /*      OFS_GOLD_FLAGS */ "obj_f_gold_flags",
    /*      OFS_FOOD_FLAGS */ "obj_f_food_flags",
    /*    OFS_SCROLL_FLAGS */ "obj_f_scroll_flags",
    /*  OFS_KEY_RING_FLAGS */ "obj_f_key_ring_flags",
    /*   OFS_WRITTEN_FLAGS */ "obj_f_written_flags",
    /*   OFS_GENERIC_FLAGS */ "obj_f_generic_flags",
    /*   OFS_CRITTER_FLAGS */ "obj_f_critter_flags",
    /*  OFS_CRITTER_FLAGS2 */ "obj_f_critter_flags2",
    /*        OFS_PC_FLAGS */ "obj_f_pc_flags",
    /*       OFS_NPC_FLAGS */ "obj_f_npc_flags",
    /*      OFS_TRAP_FLAGS */ "obj_f_trap_flags",
};

// 0x5BA010
int obj_flags_fields_lookup_tbl_values[OFS_COUNT] = {
    /*           OFS_FLAGS */ OBJ_F_FLAGS,
    /*     OFS_SPELL_FLAGS */ OBJ_F_SPELL_FLAGS,
    /*      OFS_WALL_FLAGS */ OBJ_F_WALL_FLAGS,
    /*    OFS_PORTAL_FLAGS */ OBJ_F_PORTAL_FLAGS,
    /* OFS_CONTAINER_FLAGS */ OBJ_F_CONTAINER_FLAGS,
    /*   OFS_SCENERY_FLAGS */ OBJ_F_SCENERY_FLAGS,
    /*      OFS_ITEM_FLAGS */ OBJ_F_ITEM_FLAGS,
    /*    OFS_WEAPON_FLAGS */ OBJ_F_WEAPON_FLAGS,
    /*      OFS_AMMO_FLAGS */ OBJ_F_AMMO_FLAGS,
    /*     OFS_ARMOR_FLAGS */ OBJ_F_ARMOR_FLAGS,
    /*      OFS_GOLD_FLAGS */ OBJ_F_GOLD_FLAGS,
    /*      OFS_FOOD_FLAGS */ OBJ_F_FOOD_FLAGS,
    /*    OFS_SCROLL_FLAGS */ OBJ_F_SCROLL_FLAGS,
    /*  OFS_KEY_RING_FLAGS */ OBJ_F_KEY_RING_FLAGS,
    /*   OFS_WRITTEN_FLAGS */ OBJ_F_WRITTEN_FLAGS,
    /*   OFS_GENERIC_FLAGS */ OBJ_F_GENERIC_FLAGS,
    /*   OFS_CRITTER_FLAGS */ OBJ_F_CRITTER_FLAGS,
    /*  OFS_CRITTER_FLAGS2 */ OBJ_F_CRITTER_FLAGS2,
    /*        OFS_PC_FLAGS */ OBJ_F_PC_FLAGS,
    /*       OFS_NPC_FLAGS */ OBJ_F_NPC_FLAGS,
    /*      OFS_TRAP_FLAGS */ OBJ_F_TRAP_FLAGS,
};

// 0x5BA064
const char** obj_flags_tbl[OFS_COUNT] = {
    /*           OFS_FLAGS */ obj_flags_of,
    /*     OFS_SPELL_FLAGS */ obj_flags_ofs,
    /*      OFS_WALL_FLAGS */ obj_flags_owaf,
    /*    OFS_PORTAL_FLAGS */ obj_flags_opf,
    /* OFS_CONTAINER_FLAGS */ obj_flags_ocof,
    /*   OFS_SCENERY_FLAGS */ obj_flags_oscf,
    /*      OFS_ITEM_FLAGS */ obj_flags_oif,
    /*    OFS_WEAPON_FLAGS */ obj_flags_owf,
    /*      OFS_AMMO_FLAGS */ obj_flags_oaf,
    /*     OFS_ARMOR_FLAGS */ obj_flags_oarf,
    /*      OFS_GOLD_FLAGS */ obj_flags_ogof,
    /*      OFS_FOOD_FLAGS */ obj_flags_off,
    /*    OFS_SCROLL_FLAGS */ obj_flags_osrf,
    /*  OFS_KEY_RING_FLAGS */ obj_flags_okrf,
    /*   OFS_WRITTEN_FLAGS */ obj_flags_owrf,
    /*   OFS_GENERIC_FLAGS */ obj_flags_ogf,
    /*   OFS_CRITTER_FLAGS */ obj_flags_ocf,
    /*  OFS_CRITTER_FLAGS2 */ obj_flags_ocf2,
    /*        OFS_PC_FLAGS */ obj_flags_opcf,
    /*       OFS_NPC_FLAGS */ obj_flags_onf,
    /*      OFS_TRAP_FLAGS */ obj_flags_otf,
};

// 0x5BA0B8
int obj_flags_size_tbl[OFS_COUNT] = {
    /*           OFS_FLAGS */ OF_COUNT,
    /*     OFS_SPELL_FLAGS */ OSF_COUNT,
    /*      OFS_WALL_FLAGS */ OWAF_COUNT,
    /*    OFS_PORTAL_FLAGS */ OPF_COUNT,
    /* OFS_CONTAINER_FLAGS */ OCOF_COUNT,
    /*   OFS_SCENERY_FLAGS */ OSCF_COUNT,
    /*      OFS_ITEM_FLAGS */ OIF_COUNT,
    /*    OFS_WEAPON_FLAGS */ OWF_COUNT,
    /*      OFS_AMMO_FLAGS */ OAF_COUNT,
    /*     OFS_ARMOR_FLAGS */ OARF_COUNT,
    /*      OFS_GOLD_FLAGS */ OGOF_COUNT,
    /*      OFS_FOOD_FLAGS */ OFF_COUNT,
    /*    OFS_SCROLL_FLAGS */ OSRF_COUNT,
    /*  OFS_KEY_RING_FLAGS */ OKRF_COUNT,
    /*   OFS_WRITTEN_FLAGS */ OWRF_COUNT,
    /*   OFS_GENERIC_FLAGS */ OGF_COUNT,
    /*   OFS_CRITTER_FLAGS */ OCF_COUNT,
    /*  OFS_CRITTER_FLAGS2 */ OCF2_COUNT,
    /*        OFS_PC_FLAGS */ OPCF_COUNT,
    /*       OFS_NPC_FLAGS */ ONF_COUNT,
    /*      OFS_TRAP_FLAGS */ OTF_COUNT,
};

// 0x5BA10C
const char* obj_flags_of[OF_COUNT] = {
    STRINGIFY(OF_DESTROYED),
    STRINGIFY(OF_OFF),
    STRINGIFY(OF_FLAT),
    STRINGIFY(OF_TEXT),
    STRINGIFY(OF_SEE_THROUGH),
    STRINGIFY(OF_SHOOT_THROUGH),
    STRINGIFY(OF_TRANSLUCENT),
    STRINGIFY(OF_SHRUNK),
    STRINGIFY(OF_DONTDRAW),
    STRINGIFY(OF_INVISIBLE),
    STRINGIFY(OF_NO_BLOCK),
    STRINGIFY(OF_CLICK_THROUGH),
    STRINGIFY(OF_INVENTORY),
    STRINGIFY(OF_DYNAMIC),
    STRINGIFY(OF_PROVIDES_COVER),
    STRINGIFY(OF_HAS_OVERLAYS),
    STRINGIFY(OF_HAS_UNDERLAYS),
    STRINGIFY(OF_WADING),
    STRINGIFY(OF_WATER_WALKING),
    STRINGIFY(OF_STONED),
    STRINGIFY(OF_DONTLIGHT),
    STRINGIFY(OF_TEXT_FLOATER),
    STRINGIFY(OF_INVULNERABLE),
    STRINGIFY(OF_EXTINCT),
    STRINGIFY(OF_TRAP_PC),
    STRINGIFY(OF_TRAP_SPOTTED),
    STRINGIFY(OF_DISALLOW_WADING),
    STRINGIFY(OF_MULTIPLAYER_LOCK),
    STRINGIFY(OF_FROZEN),
    STRINGIFY(OF_ANIMATED_DEAD),
    STRINGIFY(OF_TELEPORTED),
};

// 0x5BA188
const char* obj_flags_ofs[OSF_COUNT] = {
    STRINGIFY(OSF_INVISIBLE),
    STRINGIFY(OSF_FLOATING),
    STRINGIFY(OSF_BODY_OF_AIR),
    STRINGIFY(OSF_BODY_OF_EARTH),
    STRINGIFY(OSF_BODY_OF_FIRE),
    STRINGIFY(OSF_BODY_OF_WATER),
    STRINGIFY(OSF_DETECTING_MAGIC),
    STRINGIFY(OSF_DETECTING_ALIGNMENT),
    STRINGIFY(OSF_DETECTING_TRAPS),
    STRINGIFY(OSF_DETECTING_INVISIBLE),
    STRINGIFY(OSF_SHIELDED),
    STRINGIFY(OSF_ANTI_MAGIC_SHELL),
    STRINGIFY(OSF_BONDS_OF_MAGIC),
    STRINGIFY(OSF_FULL_REFLECTION),
    STRINGIFY(OSF_SUMMONED),
    STRINGIFY(OSF_ILLUSION),
    STRINGIFY(OSF_STONED),
    STRINGIFY(OSF_POLYMORPHED),
    STRINGIFY(OSF_MIRRORED),
    STRINGIFY(OSF_SHRUNK),
    STRINGIFY(OSF_PASSWALLED),
    STRINGIFY(OSF_WATER_WALKING),
    STRINGIFY(OSF_MAGNETIC_INVERSION),
    STRINGIFY(OSF_CHARMED),
    STRINGIFY(OSF_ENTANGLED),
    STRINGIFY(OSF_SPOKEN_WITH_DEAD),
    STRINGIFY(OSF_TEMPUS_FUGIT),
    STRINGIFY(OSF_MIND_CONTROLLED),
    STRINGIFY(OSF_DRUNK),
    STRINGIFY(OSF_ENSHROUDED),
    STRINGIFY(OSF_FAMILIAR),
    STRINGIFY(OSF_HARDENED_HANDS),
};

// 0x5BA208
const char* obj_flags_owaf[OWAF_COUNT] = {
    STRINGIFY(OWAF_TRANS_DISALLOW),
    STRINGIFY(OWAF_TRANS_LEFT),
    STRINGIFY(OWAF_TRANS_RIGHT),
    STRINGIFY(OWAF_TRANS_ALL),
};

// 0x5BA218
const char* obj_flags_opf[OPF_COUNT] = {
    STRINGIFY(OPF_LOCKED),
    STRINGIFY(OPF_JAMMED),
    STRINGIFY(OPF_MAGICALLY_HELD),
    STRINGIFY(OPF_NEVER_LOCKED),
    STRINGIFY(OPF_ALWAYS_LOCKED),
    STRINGIFY(OPF_LOCKED_DAY),
    STRINGIFY(OPF_LOCKED_NIGHT),
    STRINGIFY(OPF_BUSTED),
    STRINGIFY(OPF_STICKY),
};

// 0x5BA23C
const char* obj_flags_ocof[OCOF_COUNT] = {
    STRINGIFY(OCOF_LOCKED),
    STRINGIFY(OCOF_JAMMED),
    STRINGIFY(OCOF_MAGICALLY_HELD),
    STRINGIFY(OCOF_NEVER_LOCKED),
    STRINGIFY(OCOF_ALWAYS_LOCKED),
    STRINGIFY(OCOF_LOCKED_DAY),
    STRINGIFY(OCOF_LOCKED_NIGHT),
    STRINGIFY(OCOF_BUSTED),
    STRINGIFY(OCOF_STICKY),
};

// 0x5BA260
const char* obj_flags_oscf[OSCF_COUNT] = {
    STRINGIFY(OSCF_NO_AUTO_ANIMATE),
    STRINGIFY(OSCF_BUSTED),
    STRINGIFY(OSCF_NOCTURNAL),
    STRINGIFY(OSCF_MARKS_TOWNMAP),
    STRINGIFY(OSCF_IS_FIRE),
    STRINGIFY(OSCF_RESPAWNABLE),
    STRINGIFY(OSCF_SOUND_SMALL),
    STRINGIFY(OSCF_SOUND_MEDIUM),
    STRINGIFY(OSCF_SOUND_EXTRA_LARGE),
};

// 0x5BA284
const char* obj_flags_oif[OIF_COUNT] = {
    STRINGIFY(OIF_IDENTIFIED),
    STRINGIFY(OIF_WONT_SELL),
    STRINGIFY(OIF_IS_MAGICAL),
    STRINGIFY(OIF_TRANSFER_LIGHT),
    STRINGIFY(OIF_NO_DISPLAY),
    STRINGIFY(OIF_NO_DROP),
    STRINGIFY(OIF_HEXED),
    STRINGIFY(OIF_CAN_USE_BOX),
    STRINGIFY(OIF_NEEDS_TARGET),
    STRINGIFY(OIF_LIGHT_SMALL),
    STRINGIFY(OIF_LIGHT_MEDIUM),
    STRINGIFY(OIF_LIGHT_LARGE),
    STRINGIFY(OIF_LIGHT_XLARGE),
    STRINGIFY(OIF_PERSISTENT),
    STRINGIFY(OIF_MT_TRIGGERED),
    STRINGIFY(OIF_STOLEN),
    STRINGIFY(OIF_USE_IS_THROW),
    STRINGIFY(OIF_NO_DECAY),
    STRINGIFY(OIF_UBER),
    STRINGIFY(OIF_NO_NPC_PICKUP),
    STRINGIFY(OIF_NO_RANGED_USE),
    STRINGIFY(OIF_VALID_AI_ACTION),
    STRINGIFY(OIF_MP_INSERTED),
};

// 0x5BA2E0
const char* obj_flags_owf[OWF_COUNT] = {
    STRINGIFY(OWF_LOUD),
    STRINGIFY(OWF_SILENT),
    STRINGIFY(OWF_TWO_HANDED),
    STRINGIFY(OWF_HAND_COUNT_FIXED),
    STRINGIFY(OWF_THROWABLE),
    STRINGIFY(OWF_TRANS_PROJECTILE),
    STRINGIFY(OWF_BOOMERANGS),
    STRINGIFY(OWF_IGNORE_RESISTANCE),
    STRINGIFY(OWF_DAMAGE_ARMOR),
    STRINGIFY(OWF_DEFAULT_THROWS),
};

// 0x5BA308
const char* obj_flags_oaf[OAF_COUNT] = {
    STRINGIFY(OAF_NONE),
};

// 0x5BA30C
const char* obj_flags_oarf[OARF_COUNT] = {
    STRINGIFY(OARF_SIZE_SMALL),
    STRINGIFY(OARF_SIZE_MEDIUM),
    STRINGIFY(OARF_SIZE_LARGE),
    STRINGIFY(OARF_MALE_ONLY),
    STRINGIFY(OARF_FEMALE_ONLY),
};

// 0x5BA320
const char* obj_flags_ogof[OGOF_COUNT] = {
    STRINGIFY(OGOF_NONE),
};

// 0x5BA324
const char* obj_flags_off[OFF_COUNT] = {
    STRINGIFY(OFF_NONE),
};

// 0x5BA328
const char* obj_flags_osrf[OSRF_COUNT] = {
    STRINGIFY(OSRF_NONE),
};

// 0x5BA32C
const char* obj_flags_okrf[OKRF_COUNT] = {
    STRINGIFY(OKRF_PRIMARY_RING),
};

// 0x5BA330
const char* obj_flags_owrf[OWRF_COUNT] = {
    STRINGIFY(OWRF_NONE),
};

// 0x5BA334
const char* obj_flags_ogf[OGF_COUNT] = {
    STRINGIFY(OGF_USES_TORCH_SHIELD_LOCATION),
    STRINGIFY(OGF_IS_LOCKPICK),
    STRINGIFY(OGF_IS_TRAP_DEVICE),
    NULL,
    NULL,
};

// 0x5BA348
const char* obj_flags_ocf[OCF_COUNT] = {
    STRINGIFY(OCF_IS_CONCEALED),
    STRINGIFY(OCF_MOVING_SILENTLY),
    STRINGIFY(OCF_UNDEAD),
    STRINGIFY(OCF_ANIMAL),
    STRINGIFY(OCF_FLEEING),
    STRINGIFY(OCF_STUNNED),
    STRINGIFY(OCF_PARALYZED),
    STRINGIFY(OCF_BLINDED),
    STRINGIFY(OCF_CRIPPLED_ARMS_ONE),
    STRINGIFY(OCF_CRIPPLED_ARMS_BOTH),
    STRINGIFY(OCF_CRIPPLED_LEGS_BOTH),
    STRINGIFY(OCF_UNUSED),
    STRINGIFY(OCF_SLEEPING),
    STRINGIFY(OCF_MUTE),
    STRINGIFY(OCF_SURRENDERED),
    STRINGIFY(OCF_MONSTER),
    STRINGIFY(OCF_SPELL_FLEE),
    STRINGIFY(OCF_ENCOUNTER),
    STRINGIFY(OCF_COMBAT_MODE_ACTIVE),
    STRINGIFY(OCF_LIGHT_SMALL),
    STRINGIFY(OCF_LIGHT_MEDIUM),
    STRINGIFY(OCF_LIGHT_LARGE),
    STRINGIFY(OCF_LIGHT_XLARGE),
    STRINGIFY(OCF_UNREVIVIFIABLE),
    STRINGIFY(OCF_UNRESSURECTABLE),
    STRINGIFY(OCF_DEMON),
    STRINGIFY(OCF_FATIGUE_IMMUNE),
    STRINGIFY(OCF_NO_FLEE),
    STRINGIFY(OCF_NON_LETHAL_COMBAT),
    STRINGIFY(OCF_MECHANICAL),
    STRINGIFY(OCF_ANIMAL_ENSHROUD),
    STRINGIFY(OCF_FATIGUE_LIMITING),
};

// 0x5BA3C8
const char* obj_flags_ocf2[OCF2_COUNT] = {
    STRINGIFY(OCF2_ITEM_STOLEN),
    STRINGIFY(OCF2_AUTO_ANIMATES),
    STRINGIFY(OCF2_USING_BOOMERANG),
    STRINGIFY(OCF2_FATIGUE_DRAINING),
    STRINGIFY(OCF2_SLOW_PARTY),
    STRINGIFY(OCF2_COMBAT_TOGGLE_FX),
    STRINGIFY(OCF2_NO_DECAY),
    STRINGIFY(OCF2_NO_PICKPOCKET),
    STRINGIFY(OCF2_NO_BLOOD_SPLOTCHES),
    STRINGIFY(OCF2_NIGH_INVULNERABLE),
    STRINGIFY(OCF2_ELEMENTAL),
    STRINGIFY(OCF2_DARK_SIGHT),
    STRINGIFY(OCF2_NO_SLIP),
    STRINGIFY(OCF2_NO_DISINTEGRATE),
    STRINGIFY(OCF2_REACTION_0),
    STRINGIFY(OCF2_REACTION_1),
    STRINGIFY(OCF2_REACTION_2),
    STRINGIFY(OCF2_REACTION_3),
    STRINGIFY(OCF2_REACTION_4),
    STRINGIFY(OCF2_REACTION_5),
    STRINGIFY(OCF2_REACTION_6),
    STRINGIFY(OCF2_TARGET_LOCK),
    STRINGIFY(OCF2_PERMA_POLYMORPH),
    STRINGIFY(OCF2_SAFE_OFF),
    STRINGIFY(OCF2_CHECK_REACTION_BAD),
    STRINGIFY(OCF2_CHECK_ALIGN_GOOD),
    STRINGIFY(OCF2_CHECK_ALIGN_BAD),
};

// 0x5BA434
const char* obj_flags_opcf[OPCF_COUNT] = {
    STRINGIFY(OPCF_unused_1),
    STRINGIFY(OPCF_unused_2),
    STRINGIFY(OPCF_USE_ALT_DATA),
    STRINGIFY(OPCF_unused_4),
    STRINGIFY(OPCF_unused_5),
    STRINGIFY(OPCF_FOLLOWER_SKILLS_ON),
};

// 0x5BA44C
const char* obj_flags_onf[ONF_COUNT] = {
    STRINGIFY(ONF_FIGHTING),
    STRINGIFY(ONF_WAYPOINTS_DAY),
    STRINGIFY(ONF_WAYPOINTS_NIGHT),
    STRINGIFY(ONF_AI_WAIT_HERE),
    STRINGIFY(ONF_AI_SPREAD_OUT),
    STRINGIFY(ONF_JILTED),
    STRINGIFY(ONF_CHECK_WIELD),
    STRINGIFY(ONF_CHECK_WEAPON),
    STRINGIFY(ONF_KOS),
    STRINGIFY(ONF_WAYPOINTS_BED),
    STRINGIFY(ONF_FORCED_FOLLOWER),
    STRINGIFY(ONF_KOS_OVERRIDE),
    STRINGIFY(ONF_WANDERS),
    STRINGIFY(ONF_WANDERS_IN_DARK),
    STRINGIFY(ONF_FENCE),
    STRINGIFY(ONF_FAMILIAR),
    STRINGIFY(ONF_CHECK_LEADER),
    STRINGIFY(ONF_ALOOF),
    STRINGIFY(ONF_CAST_HIGHEST),
    STRINGIFY(ONF_GENERATOR),
    STRINGIFY(ONF_GENERATED),
    STRINGIFY(ONF_GENERATOR_RATE1),
    STRINGIFY(ONF_GENERATOR_RATE2),
    STRINGIFY(ONF_GENERATOR_RATE3),
    STRINGIFY(ONF_DEMAINTAIN_SPELLS),
    STRINGIFY(ONF_LOOK_FOR_WEAPON),
    STRINGIFY(ONF_LOOK_FOR_ARMOR),
    STRINGIFY(ONF_LOOK_FOR_AMMO),
    STRINGIFY(ONF_BACKING_OFF),
    STRINGIFY(ONF_NO_ATTACK),
    NULL,
};

// 0x5BA4C8
const char* obj_flags_otf[OTF_COUNT] = {
    STRINGIFY(OTF_BUSTED),
};
