#ifndef ARCANUM_GAME_SND_H_
#define ARCANUM_GAME_SND_H_

#define SND_INTERFACE_BUTTON_MEDIUM 3000
#define SND_INTERFACE_BUTTON_MEDIUM_RELEASE 3001
#define SND_INTERFACE_BLESS 3002
#define SND_INTERFACE_CURSED 3003
#define SND_INTERFACE_EXCLAMATION 3004
#define SND_INTERFACE_LEVEL_UP 3005
#define SND_INTERFACE_POISONED 3006
#define SND_INTERFACE_ITEM_DROP 3007
#define SND_INTERFACE_BOOK_OPEN 3008
#define SND_INTERFACE_BOOK_CLOSE 3009
#define SND_INTERFACE_BOOK_PAGE_TURN 3010
#define SND_INTERFACE_BOOK_SWITCH 3011
#define SND_INTERFACE_BUTTON_HIGH 3012
#define SND_INTERFACE_BUTTON_HIGH_RELEASE 3013
#define SND_INTERFACE_BUTTON_LOW 3014
#define SND_INTERFACE_BUTTON_LOW_RELEASE 3015
#define SND_INTERFACE_BUTTON_METAL 3016
#define SND_INTERFACE_BUTTON_METAL_RELEASE 3017
#define SND_INTERFACE_COM_HERBAL 3018
#define SND_INTERFACE_COM_CHEMISTRY 3019
#define SND_INTERFACE_COM_ELECTRICAL 3020
#define SND_INTERFACE_COM_EXPLOSIVE 3021
#define SND_INTERFACE_COM_GUN 3022
#define SND_INTERFACE_COM_MECHANICAL 3023
#define SND_INTERFACE_COM_SMITHY 3024
#define SND_INTERFACE_COM_THERAPEUTICS 3025
#define SND_INTERFACE_MORPHTEXT_HOVER 3026
#define SND_INTERFACE_MORPHTEXT_CLICK 3027
#define SND_INTERFACE_QUESTCOMPLETE 3028

#endif /* ARCANUM_GAME_SND_H_ */
